version: '3.9'
services:
  database:
    image: "postgres"
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - "database:/var/lib/postgresql/data"
    env_file:
      - ./env/database.env
    
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "5050:80"
    env_file:
      - ./env/pgadmin.env
    depends_on:
      - database

  backend:
    build: ./backend/
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - database

volumes:
  database:


